name: Har Pito
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
    - name: Download startup files
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/Harchanel15/insyaallah-gak-ke-banned-akun-kalian/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Harchanel15/insyaallah-gak-ke-banned-akun-kalian/main/wallpaper.bat -OutFile wallpaper.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Harchanel15/insyaallah-gak-ke-banned-akun-kalian/main/loop.bat -OutFile loop.bat

    - name: Setup Windows RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        netsh advfirewall firewall add rule name="Allow RDP Port 3389" dir=in action=allow protocol=TCP localport=3389
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.bat D:\a\wallpaper.bat

    # --- Tailscale Steps Start Here ---
    - name: Install Tailscale using Chocolatey
      run: choco install tailscale --yes
    
    - name: Connect to Tailscale
      env:
        TS_AUTHKEY: ${{ secrets.TS_AUTHKEY }}
      run: |
        # Using the more reliable PowerShell variable syntax
        & "C:\Program Files\Tailscale\tailscale.exe" up --authkey="$env:TS_AUTHKEY"

    - name: Get Tailscale IP Address
      id: tailscale_ip
      run: |
        $ip = & "C:\Program Files\Tailscale\tailscale.exe" ip -4
        echo "Tailscale IP: $ip"
        echo "ip=$ip" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
    # --- Tailscale Steps End Here ---

    - name: Start RDP setup
      run: cmd /c start.bat

    - name: Keep session alive
      run: cmd /c loop.bat
